In [1]:
import pandas as pd
data = {'Name': ['Shiv', 'Vishnu', 'Lakshmi', 'Saras'],
        'Age': [25, None, 30, None],
        'Gender': ['M', 'M', None, 'F']}
print(data)

{'Name': ['Shiv', 'Vishnu', 'Lakshmi', 'Saras'], 'Age': [25, None, 30, None], 'Gender': ['M', 'M', None, 'F']}

In [2]:
df = pd.DataFrame(data)
print(df)

      Name   Age Gender
0     Shiv  25.0      M
1   Vishnu   NaN      M
2  Lakshmi  30.0   None
3    Saras   NaN      F

Step-by-Step Data Cleaning Methods

Check for Missing Data bold text

Shows which cells are missing (True)
Summarizes how many missing values per column -- isna()

In [3]:
df.isna()

    Name    Age  Gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

In [4]:
df.isna()

    Name    Age  Gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

2. Drop Missing Data 🔹 Drop Rows with Any NaN

In [5]:
df.dropna()

   Name   Age Gender
0  Shiv  25.0      M

 Drop Columns with Any NaN

In [6]:
df.dropna(axis=1)

      Name
0     Shiv
1   Vishnu
2  Lakshmi
3    Saras

 Drop Rows with Missing in Specific Column

In [7]:
 df.dropna(subset=['Age'])

      Name   Age Gender
0     Shiv  25.0      M
2  Lakshmi  30.0   None

In [8]:
df.at[1,'Gender']='F'
df

      Name   Age Gender
0     Shiv  25.0      M
1   Vishnu   NaN      F
2  Lakshmi  30.0   None
3    Saras   NaN      F

Fill Missing Data (Imputation) 🔹 Fill with a Constan

In [9]:
df.fillna(0)

      Name   Age Gender
0     Shiv  25.0      M
1   Vishnu   0.0      F
2  Lakshmi  30.0      0
3    Saras   0.0      F

Mean/Median/Mode

In [10]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

/tmp/ipython-input-3663963327.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipython-input-3663963327.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

Detect Duplicates

In [11]:
df.duplicated()
#df.drop_duplicates()

0    False
1    False
2    False
3    False
dtype: bool

In [12]:
df.drop_duplicates()

      Name   Age Gender
0     Shiv  25.0      M
1   Vishnu  27.5      F
2  Lakshmi  30.0      F
3    Saras  27.5      F

Convert Data Types

In [13]:
df['Age'] = df['Age'].astype(int)

6. Rename Columns

In [ ]:
df.rename(columns={'Name': 'FullName'}, inplace=True)
df      upper()----lower()

  FullName   Age Gender
0     Shiv  25.0      M
1   Vishnu   NaN      M
2  Lakshmi  30.0   None
3    Saras   NaN      F

7. Standardize Text

In [ ]:
df['FullName'] = df['FullName'].str.upper()
df

  FullName   Age Gender
0     SHIV  25.0      M
1   VISHNU   NaN      M
2  LAKSHMI  30.0   None
3    SARAS   NaN      F

8.Remove Outliers (Optional)

In [28]:
df = df[df['Age'] < 100]  # Example filter

In [29]:
df

      Name  Age Gender
0     Shiv   25      M
1   Vishnu   27      F
2  Lakshmi   30      F
3    Saras   27      F

USING CSV FILE

In [30]:
import pandas as pd

In [32]:
df = pd.read_csv('/content/Book1.csv')

In [33]:
print(df)

   Name  Age  Salary
0  abhi   21  289999