In [15]:
import pandas as pd
data = {'Name': ['Geethika', 'Priya', 'Lakshmi', 'Sarath'],
        'Age': [25, None, 30, None],
        'Gender': ['F', 'F', None, 'M']}
print(data)

{'Name': ['Geethika', 'Priya', 'Lakshmi', 'Sarath'], 'Age': [25, None, 30, None], 'Gender': ['F', 'F', None, 'M']}

In [16]:
df = pd.DataFrame(data)
print(df)

       Name   Age Gender
0  Geethika  25.0      F
1     Priya   NaN      F
2   Lakshmi  30.0   None
3    Sarath   NaN      M

Step-by-Step Data Cleaning Methods

Check for Missing Data

Shows which cells are missing (True)
Summarizes how many missing values per column -- isna()

In [17]:
df.isna()

    Name    Age  Gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

In [18]:
df.isna()

    Name    Age  Gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

2. Drop Missing Data 🔹 Drop Rows with Any NaN

In [19]:
df.dropna()

       Name   Age Gender
0  Geethika  25.0      F

 Drop Columns with Any NaN

In [20]:
df.dropna(axis=1)

       Name
0  Geethika
1     Priya
2   Lakshmi
3    Sarath

 Drop Rows with Missing in Specific Column

In [21]:
 df.dropna(subset=['Age'])

       Name   Age Gender
0  Geethika  25.0      F
2   Lakshmi  30.0   None

In [22]:
df.at[1,'Gender']='F'
df

       Name   Age Gender
0  Geethika  25.0      F
1     Priya   NaN      F
2   Lakshmi  30.0   None
3    Sarath   NaN      M

Fill Missing Data (Imputation) 🔹 Fill with a Constan

In [23]:
df.fillna(0)

       Name   Age Gender
0  Geethika  25.0      F
1     Priya   0.0      F
2   Lakshmi  30.0      0
3    Sarath   0.0      M

Mean/Median/Mode

In [24]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

/tmp/ipython-input-3663963327.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipython-input-3663963327.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

Detect Duplicates

In [25]:
df.duplicated()
#df.drop_duplicates()

0    False
1    False
2    False
3    False
dtype: bool

In [26]:
df.drop_duplicates()

       Name   Age Gender
0  Geethika  25.0      F
1     Priya  27.5      F
2   Lakshmi  30.0      F
3    Sarath  27.5      M

Convert Data Types

In [27]:
df['Age'] = df['Age'].astype(int)

6. Rename Columns

In [29]:
df.rename(columns={'Name': 'FullName'}, inplace=True)
df

   FullName  Age Gender
0  Geethika   25      F
1     Priya   27      F
2   Lakshmi   30      F
3    Sarath   27      M

7. Standardize Text

In [ ]:
df['FullName'] = df['FullName'].str.upper()
df

8.Remove Outliers (Optional)

In [ ]:
df = df[df['Age'] < 100]  # Example filter

In [ ]:
df

USING CSV FILE

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Book1.csv')

In [ ]:
print(df)