<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/bhaskar/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
left = pd.DataFrame({"key":["K0", "K1", "K2", "K3"],
                     "A":["A0", "A1", "A2", "A3"],
                     "B":["B0", "B1", "B2", "B3"],
})
right = pd.DataFrame({"key":["K0", "K1", "K2", "K3"],
                      "C":["C0", "C1", "C2", "C3"],
                      "D":["D0", "D1", "D2", "D3"],
})
result = pd.merge(left, right, on="key")

result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [ ]:
import pandas as pd
left = pd.DataFrame(
    {"key1":["K0", "K0", "K1", "K2"],
     "key2":["K0", "K1", "K0", "K1"],
     "A":["A0", "A1", "A2", "A3"],
     "B":["B0", "B1", "B2", "B3"],
    })
right = pd.DataFrame(
    {"key1":["K0", "K1", "K1", "K2"],
     "key2":["K0", "K0", "K0", "K0"],
     "C":["C0", "C1", "C2", "C3"],
     "D":["D0", "D1", "D2", "D3"],
    })
result = pd.merge(left, right, how="left", on=["key1", "key2"])
result

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [ ]:
import pandas as pd
left = pd.DataFrame(
    {"key1":["K0", "K0", "K1", "K2"],
     "key2":["K0", "K1", "K0", "K1"],
     "A":["A0", "A1", "A2", "A3"],
     "B":["B0", "B1", "B2", "B3"],
    })
right = pd.DataFrame(
    {"key1":["K0", "K1", "K1", "K2"],
     "key2":["K0", "K0", "K0", "K0"],
     "C":["C0", "C1", "C2", "C3"],
     "D":["D0", "D1", "D2", "D3"],
    })
result = pd.merge(left, right, how="outer", on=["key1", "key2"])
result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [ ]:
import pandas as pd
left = pd.DataFrame(
    {"key1":["K0", "K0", "K1", "K2"],
     "key2":["K0", "K1", "K0", "K1"],
     "A":["A0", "A1", "A2", "A3"],
     "B":["B0", "B1", "B2", "B3"],
    })
right = pd.DataFrame(
    {"key1":["K0", "K1", "K1", "K2"],
     "key2":["K0", "K0", "K0", "K0"],
     "C":["C0", "C1", "C2", "C3"],
     "D":["D0", "D1", "D2", "D3"],
    })
result = pd.merge(left, right, how="right", on=["key1", "key2"])
result

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [ ]:
import pandas as pd
left = pd.DataFrame(
    {"key1":["K0", "K0", "K1", "K2"],
     "key2":["K0", "K1", "K0", "K1"],
     "A":["A0", "A1", "A2", "A3"],
     "B":["B0", "B1", "B2", "B3"],
    })
right = pd.DataFrame(
    {"key1":["K0", "K1", "K1", "K2"],
     "key2":["K0", "K0", "K0", "K0"],
     "C":["C0", "C1", "C2", "C3"],
     "D":["D0", "D1", "D2", "D3"],
    })
result = pd.merge(left, right, how="inner", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [ ]:
import pandas as pd
data = {'Name':["Bhaskar", "surya", "pavan","lakshmi"],
        'Age':[23,20,21,25],
        'marks':[None, 75,69,85]}
print(data)

{'Name': ['Bhaskar', 'surya', 'pavan', 'lakshmi'], 'Age': [23, 20, 21, 25], 'marks': [None, 75, 69, 85]}

In [ ]:
df=pd.DataFrame(data)
print(df)

      Name  Age  marks
0  Bhaskar   23    NaN
1    surya   20   75.0
2    pavan   21   69.0
3  lakshmi   25   85.0

In [ ]:
df.isna()

    Name    Age  marks
0  False  False   True
1  False  False  False
2  False  False  False
3  False  False  False

In [ ]:
df.isna().sum()

Name     0
Age      0
marks    1
dtype: int64

In [ ]:
df.dropna()

      Name  Age  marks
1    surya   20   75.0
2    pavan   21   69.0
3  lakshmi   25   85.0

In [ ]:
df.dropna(axis=True)

      Name  Age
0  Bhaskar   23
1    surya   20
2    pavan   21
3  lakshmi   25

In [ ]:
df.dropna(axis=0)

      Name  Age  marks
1    surya   20   75.0
2    pavan   21   69.0
3  lakshmi   25   85.0

In [ ]:
df.dropna(subset="marks")

      Name  Age  marks
1    surya   20   75.0
2    pavan   21   69.0
3  lakshmi   25   85.0

In [ ]:
df.at[2,'marks']=85
df

      Name  Age  marks
0  Bhaskar   23    NaN
1    surya   20   75.0
2    pavan   21   85.0
3  lakshmi   25   85.0

In [ ]:
df.fillna(28.999)

      Name  Age   marks
0  Bhaskar   23  28.999
1    surya   20  75.000
2    pavan   21  85.000
3  lakshmi   25  85.000

In [ ]:
df.rename(columns={"Name":"Student"}, inplace=True)
df

   Student  Age  marks
0  Bhaskar   23    NaN
1    surya   20   75.0
2    pavan   21   85.0
3  lakshmi   25   85.0

In [ ]:
df['Student']= df['Student'].str.upper()
df

   Student  Age  marks
0  BHASKAR   23    NaN
1    SURYA   20   75.0
2    PAVAN   21   85.0
3  LAKSHMI   25   85.0

In [ ]:
df['Student']= df['Student'].str.lower()
df

   Student  Age  marks
0  bhaskar   23    NaN
1    surya   20   75.0
2    pavan   21   85.0
3  lakshmi   25   85.0

In [ ]:
import pandas as pd
a=pd.read_csv('/content/infosys.csv')
print(a)

   rool number     name  age  marks
0           56  bhaskar   21     35
1           57     raju   21     35

In [ ]:
import pandas as pd
data = {'student':['bhaskar','ram','pavan','swapna','geetha','surya','bhaskar'],
        'age':[24,23,22,23,23,'nan','nan'],
        'rool_no':[56,57,58,59,50,60,76],
        'marks':[60,75,90,55,'nan',66,77]}
df=pd.DataFrame(data)
df.to_csv('first.csv',index=False)
print(data)

{'student': ['bhaskar', 'ram', 'pavan', 'swapna', 'geetha', 'surya', 'bhaskar'], 'age': [24, 23, 22, 23, 23, 'nan', 'nan'], 'rool_no': [56, 57, 58, 59, 50, 60, 76], 'marks': [60, 75, 90, 55, 'nan', 66, 77]}

In [ ]:
import pandas as pd
a=pd.read_csv('/content/first.csv')
print(a)

   student   age  rool_no  marks
0  bhaskar  24.0       56   60.0
1      ram  23.0       57   75.0
2    pavan  22.0       58   90.0
3   swapna  23.0       59   55.0
4   geetha  23.0       50    NaN
5    surya   NaN       60   66.0
6  bhaskar   NaN       76   77.0

In [ ]:
newdf = a.fillna(22.00)
print(newdf)

   student   age  rool_no  marks
0  bhaskar  24.0       56   60.0
1      ram  23.0       57   75.0
2    pavan  22.0       58   90.0
3   swapna  23.0       59   55.0
4   geetha  23.0       50   22.0
5    surya  22.0       60   66.0
6  bhaskar  22.0       76   77.0

In [ ]:
newdf.iloc[4,3]=85.0
newdf.iloc[5,3]=70.0
newdf

   student   age  rool_no  marks
0  bhaskar  24.0       56   60.0
1      ram  23.0       57   75.0
2    pavan  22.0       58   90.0
3   swapna  23.0       59   55.0
4   geetha  23.0       50   85.0
5    surya  22.0       60   70.0
6  bhaskar  22.0       76   77.0

In [ ]:
a.fillna({'age':22,'marks':85},inplace=False)

   student   age  rool_no  marks
0  bhaskar  24.0       56   60.0
1      ram  23.0       57   75.0
2    pavan  22.0       58   90.0
3   swapna  23.0       59   55.0
4   geetha  23.0       50   85.0
5    surya  22.0       60   66.0
6  bhaskar  22.0       76   77.0

In [ ]:
print(a.duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [ ]:
#data cleaning
df_cleaned=a.drop('age',axis=1)
df_cleaned

   student  rool_no  marks
0  bhaskar       56   60.0
1      ram       57   75.0
2    pavan       58   90.0
3   swapna       59   55.0
4   geetha       50   85.0
5    surya       60   66.0
6  bhaskar       76   77.0

In [ ]:
df_cleaned1=newdf.drop('marks',axis=1)

In [ ]:
print(df_cleaned1)

   student   age  rool_no
0  bhaskar  24.0       56
1      ram  23.0       57
2    pavan  22.0       58
3   swapna  23.0       59
4   geetha  23.0       50
5    surya  22.0       60
6  bhaskar  22.0       76

In [ ]:
missing_values = df.isnull().sum()
print(missing_values)

student    0
age        0
rool_no    0
marks      0
dtype: int64