<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/NITISHA_SHINY/InfosysSpringboardf1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Day 1

In [ ]:
import pandas as pd

left = pd.DataFrame(
    {
        "key":["k0","k1","k2","k3"],
        "A":["A0","A1","A2","A3"],
        "B":["B0","B1","B2","B3"],
    }
)

right = pd.DataFrame(
    {
        "key":["k0","k1","k2","k3"],
        "C":["C0","C1","C2","C3"],
        "D":["D0","D1","D2","D3"],
    })

res = pd.merge(left,right,on="key")
print(res)

  key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [ ]:
left = pd.DataFrame(
    {
        "key1":["k0","k1","k2","k3"],
        "key2":["k0","k1","k2","k3"],
        "A":["A0","A1","A2","A3"],
        "B":["B0","B1","B2","B3"],
    }
)

right = pd.DataFrame(
    {
        "key1":["k0","k1","k2","k3"],
        "key2":["k0","k1","k2","k3"],
        "C":["C0","C1","C2","C3"],
        "D":["D0","D1","D2","D3"],
    })

In [ ]:
res = pd.merge(left,right,how="left",on=["key1","key2"])
print(res)

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k1  A1  B1  C1  D1
2   k2   k2  A2  B2  C2  D2
3   k3   k3  A3  B3  C3  D3

In [ ]:
res = pd.merge(left,right,how="right",on=["key1","key2"])
print(res)

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k1  A1  B1  C1  D1
2   k2   k2  A2  B2  C2  D2
3   k3   k3  A3  B3  C3  D3

In [ ]:
res = pd.merge(right,left,how="outer",on=["key1","key2"])
print(res)

  key1 key2   C   D   A   B
0   k0   k0  C0  D0  A0  B0
1   k1   k1  C1  D1  A1  B1
2   k2   k2  C2  D2  A2  B2
3   k3   k3  C3  D3  A3  B3

In [ ]:
res = pd.merge(left,right,how="inner",on=["key1","key2"])
print(res)

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k1  A1  B1  C1  D1
2   k2   k2  A2  B2  C2  D2
3   k3   k3  A3  B3  C3  D3

#  DAY2

In [ ]:
cars = pd.DataFrame(
    {
        "Car":["Audi","Porche","Lambo","Mercedes"],
        "Model":["Q3","911",None,"C-Class"],
        "Seats":[5,4,2,None],
    }
)

In [ ]:
df = pd.DataFrame(cars)
df

        Car    Model  Seats
0      Audi       Q3    5.0
1    Porche      911    4.0
2     Lambo     None    2.0
3  Mercedes  C-Class    NaN

In [ ]:
df.isna()
df.isna().sum()

Car      0
Model    1
Seats    1
dtype: int64

In [ ]:
# drop the rows having NaN vals
df.dropna()

      Car Model  Seats
0    Audi    Q3    5.0
1  Porche   911    4.0

In [ ]:
# drop the cols having NaN vals
df.dropna(axis=1)

        Car
0      Audi
1    Porche
2     Lambo
3  Mercedes

In [ ]:
df.dropna(axis=0)

      Car Model  Seats
0    Audi    Q3    5.0
1  Porche   911    4.0

In [ ]:
df.dropna(subset=["Seats"])

      Car Model  Seats
0    Audi    Q3    5.0
1  Porche   911    4.0
2   Lambo  None    2.0

In [ ]:
df.dropna(subset=["Model"])

        Car    Model  Seats
0      Audi       Q3    5.0
1    Porche      911    4.0
3  Mercedes  C-Class    NaN

In [ ]:
# manipulate value (without using .iloc)
df.at[2,"Model"] = "Huracan"
df

        Car    Model  Seats
0      Audi       Q3    5.0
1    Porche      911    4.0
2     Lambo  Huracan    2.0
3  Mercedes  C-Class    NaN

In [ ]:
df.fillna(0)

        Car    Model  Seats
0      Audi       Q3    5.0
1    Porche      911    4.0
2     Lambo  Huracan    2.0
3  Mercedes  C-Class    0.0

In [ ]:
df.rename(columns={"Car":"Brand"},inplace=True)
df

      Brand    Model  Seats
0      Audi       Q3    5.0
1    Porche      911    4.0
2     Lambo  Huracan    2.0
3  Mercedes  C-Class    NaN

In [ ]:
df["Brand"] = df["Brand"].str.upper()
df

      Brand    Model  Seats
0      AUDI       Q3    5.0
1    PORCHE      911    4.0
2     LAMBO  Huracan    2.0
3  MERCEDES  C-Class    NaN

In [ ]:
df['Seats']>2

0     True
1     True
2    False
3    False
Name: Seats, dtype: bool

In [ ]:
df[df['Seats']>2]

    Brand Model  Seats
0    AUDI    Q3    5.0
1  PORCHE   911    4.0

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Day3

In [ ]:
data = {
    "Name": ["A","B","C","D","A","E"],
    "Age":[20,21,22,23,20,25],
    "Salary":[20000,30000,40000,None,20000,None],
    "Rating":[4,4.1,4.2,4.5,4,4.6]
}

df = pd.DataFrame(data)
df.to_csv("myData.csv",index=False)

In [ ]:
df = pd.read_csv("myData.csv")
df

  Name  Age   Salary  Rating
0    A   20  20000.0     4.0
1    B   21  30000.0     4.1
2    C   22  40000.0     4.2
3    D   23      NaN     4.5
4    A   20  20000.0     4.0
5    E   25      NaN     4.6

In [ ]:
newdf = df.fillna(55000)
newdf

  Name  Age   Salary  Rating
0    A   20  20000.0     4.0
1    B   21  30000.0     4.1
2    C   22  40000.0     4.2
3    D   23  55000.0     4.5
4    A   20  20000.0     4.0
5    E   25  55000.0     4.6

In [ ]:
# integer locations only
newdf.iloc[3,3] = 5.0
newdf

  Name  Age   Salary  Rating
0    A   20  20000.0     4.0
1    B   21  30000.0     4.1
2    C   22  40000.0     4.2
3    D   23  55000.0     5.0
4    A   20  20000.0     4.0
5    E   25  55000.0     4.6

In [ ]:
## integer locations only no strings
# newdf.iloc[3,"Salary"] = 60000

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
# df1.shape
df.dropna()

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df

  Name  Age   Salary  Rating
0    A   20  20000.0     4.0
1    B   21  30000.0     4.1
2    C   22  40000.0     4.2
3    D   23      NaN     4.5
4    A   20  20000.0     4.0
5    E   25      NaN     4.6

In [ ]:
df.drop_duplicates()

  Name  Age   Salary  Rating
0    A   20  20000.0     4.0
1    B   21  30000.0     4.1
2    C   22  40000.0     4.2
3    D   23      NaN     4.5
5    E   25      NaN     4.6

In [ ]:
df.isnull().sum()

Name      0
Age       0
Salary    2
Rating    0
dtype: int64