<a href="https://colab.research.google.com/github/springboardmentorLive/Reality_AI/blob/ananyarohidasshet/IS_Data_Collection_%26_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

left = pd.DataFrame (

{

"key": ["K0", "K1", "K2", "K3"], "Α": ["Α0", "A1", "A2", "Аз"], "B": ["B0", "B1", "B2", "B3"],

}

)

right = pd.DataFrame(

{

"key": ["K0", "K1", "K2", "K3"], "C": ["C0", "C1", "C2", "C3"], "D": ["D0", "D1", "D2", "D3"],

}

)

result = pd.merge(left, right, on="key")

result

  key   Α   B   C   D
0  K0  Α0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  Аз  B3  C3  D3

In [ ]:
import pandas as pd
left = pd.DataFrame(
    {
        "key1": ["K0","K1", "K2", "K3"],
        "key2": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K2", "K3"],
        "key2": ["K0", "K1", "K2", "K3"],
        "C": ["C1", "C2", "C3", "C4"],
        "D": ["D1", "D2", "D3", "D4"],
    }
)

result = pd.merge(left, right, how="left", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
result = pd.merge(left, right, how="right", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
result = pd.merge(left, right, how="inner", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
result = pd.merge(left, right, how="outer", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
import pandas as pd
data = {
    'Item_Name': ['Laptop', 'Book', 'Headphones', 'Backpack'],
    'Price': [55000, 499, None, 1200],
    'Store_Location': ['Mumbai', None, 'Bangalore', 'Delhi'],
    'Category': ['Electronics', 'Stationery', 'Electronics', 'Accessories']
}
print(data)

{'Item_Name': ['Laptop', 'Book', 'Headphones', 'Backpack'], 'Price': [55000, 499, None, 1200], 'Store_Location': ['Mumbai', None, 'Bangalore', 'Delhi'], 'Category': ['Electronics', 'Stationery', 'Electronics', 'Accessories']}

In [ ]:
df = pd.DataFrame(data)
print(df)

    Item_Name    Price Store_Location     Category
0      Laptop  55000.0         Mumbai  Electronics
1        Book    499.0           None   Stationery
2  Headphones      NaN      Bangalore  Electronics
3    Backpack   1200.0          Delhi  Accessories

Step-by-Step Data Cleaning Method
1. Check for Missing Data:
Shows which cells are missing(True)

In [ ]:
df.isna()  #it is used to check the null values in the dataframe

   Item_Name  Price  Store_Location  Category
0      False  False           False     False
1      False  False            True     False
2      False   True           False     False
3      False  False           False     False

In [ ]:
df.isna().sum() #It is like an extension of isna() where we get the sum

Item_Name         0
Price             1
Store_Location    1
Category          0
dtype: int64

2. Drop Missing Data

In [ ]:
df.dropna()  #it is used to drop the rows with null values and the output only shows the rows with zero null values

  Item_Name    Price Store_Location     Category
0    Laptop  55000.0         Mumbai  Electronics
3  Backpack   1200.0          Delhi  Accessories

Drop Columns with Nan/None or Null values

In [ ]:
df.dropna(axis = 1)

    Item_Name     Category
0      Laptop  Electronics
1        Book   Stationery
2  Headphones  Electronics
3    Backpack  Accessories

Drop Rows with Null values (default)

In [ ]:
df.dropna(axis = 0)

  Item_Name    Price Store_Location     Category
0    Laptop  55000.0         Mumbai  Electronics
3  Backpack   1200.0          Delhi  Accessories

3. Drop Rows with missing values

In [ ]:
df.dropna(subset=['Store_Location'])

    Item_Name    Price Store_Location     Category
0      Laptop  55000.0         Mumbai  Electronics
2  Headphones      NaN      Bangalore  Electronics
3    Backpack   1200.0          Delhi  Accessories

In [ ]:
df.at[3,'Price']=2000 #at method is used to update a particuar cell
df                            #at[index_no., Col_name] = new value

    Item_Name    Price Store_Location     Category
0      Laptop  55000.0         Mumbai  Electronics
1        Book    499.0           None   Stationery
2  Headphones      NaN      Bangalore  Electronics
3    Backpack   2000.0          Delhi  Accessories

4. Fill Missing values

In [ ]:
df.fillna('0')  #fillna is used to fill values wherever null values are present

    Item_Name    Price Store_Location     Category
0      Laptop  55000.0         Mumbai  Electronics
1        Book    499.0              0   Stationery
2  Headphones        0      Bangalore  Electronics
3    Backpack   2000.0          Delhi  Accessories

Rename Columns

In [ ]:
df.rename(columns={'Price': 'Cost'}, inplace=True)
df

    Item_Name     Cost Store_Location     Category
0      Laptop  55000.0         Mumbai  Electronics
1        Book    499.0           None   Stationery
2  Headphones      NaN      Bangalore  Electronics
3    Backpack   2000.0          Delhi  Accessories

In [ ]:
df['Item_Name'] =df['Item_Name'].str.upper()
df

    Item_Name     Cost Store_Location     Category
0      LAPTOP  55000.0         Mumbai  Electronics
1        BOOK    499.0           None   Stationery
2  HEADPHONES      NaN      Bangalore  Electronics
3    BACKPACK   2000.0          Delhi  Accessories

In [ ]:
df['Category'] = df['Category'].str.lower()
df

    Item_Name     Cost Store_Location     Category
0      LAPTOP  55000.0         Mumbai  electronics
1        BOOK    499.0           None   stationery
2  HEADPHONES      NaN      Bangalore  electronics
3    BACKPACK   2000.0          Delhi  accessories

5. Remove Outliers

In [ ]:
df = df[df['Cost'] < 10000]

In [ ]:
df

  Item_Name    Cost Store_Location     Category
1      BOOK   499.0           None   stationery
3  BACKPACK  2000.0          Delhi  accessories

Using CSV File

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv('/content/movies.csv')

In [ ]:
print(a)

          Movie  Year      Genre  Rating
0     Inception  2010     Sci-Fi     8.8
1       Titanic  1997    Romance     7.9
2        Avatar  2009  Adventure     7.8
3  Interstellar  2014     Sci-Fi     8.6
4         Joker  2019   Thriller     8.4

In [ ]:
import pandas as pd

data = {
    "Student_Name": ["Riya","Riya" , "Amit", "Neha", "Karan", "Sara"],
    "Age": [20, 20 , None , 21, 23, 20],
    "City": ["Mumbai", "Mumbai", "Delhi", "Bangalore", "Chennai", "Pune"],
    "Marks": [88, 88, None , 85, 90, 91]
}

df = pd.DataFrame(data)

df.to_csv("students.csv", index=False)


print(data)

{'Student_Name': ['Riya', 'Riya', 'Amit', 'Neha', 'Karan', 'Sara'], 'Age': [20, 20, None, 21, 23, 20], 'City': ['Mumbai', 'Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Pune'], 'Marks': [88, 88, None, 85, 90, 91]}

In [ ]:
import pandas as pd
df = pd.read_csv('/content/students.csv')
print("Original Data:")
print(df)

Original Data:
  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
1         Riya  20.0     Mumbai   88.0
2         Amit   NaN      Delhi    NaN
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0

In [ ]:
newdf = df.fillna(13.00)
print(newdf)

  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
1         Riya  20.0     Mumbai   88.0
2         Amit  13.0      Delhi   13.0
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0

In [ ]:
newdf.iloc[2, 3] = 100
newdf

  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
1         Riya  20.0     Mumbai   88.0
2         Amit  13.0      Delhi  100.0
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0

In [ ]:
df.fillna({'Age': 29, 'Marks': 95}, inplace=False)

  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
1         Riya  20.0     Mumbai   88.0
2         Amit  29.0      Delhi   95.0
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0

In [ ]:
print(df.duplicated())

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
df_cleaned = newdf.dropna()
df_cleaned

  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
1         Riya  20.0     Mumbai   88.0
2         Amit  13.0      Delhi  100.0
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0

In [ ]:
a = newdf.drop_duplicates()     #it is used to remove duplicates from the row
print(a)

  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
2         Amit  13.0      Delhi  100.0
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0

In [ ]:
missing_values = newdf.isnull().sum()
print(missing_values)

Student_Name    0
Age             0
City            0
Marks           0
dtype: int64

In [ ]:
print(newdf)

  Student_Name   Age       City  Marks
0         Riya  20.0     Mumbai   88.0
1         Riya  20.0     Mumbai   88.0
2         Amit  13.0      Delhi  100.0
3         Neha  21.0  Bangalore   85.0
4        Karan  23.0    Chennai   90.0
5         Sara  20.0       Pune   91.0