In [ ]:
import pandas as pd

In [ ]:
data = {
    'Name': ['Riya', 'Karan', None, 'Meena', 'Amit', None, 'Sneha', 'Vikas', 'Neha', 'Tina'],
    'Age': [28, 30, 22, None, 26, 21, None, 24, 29, None],
    'Gender': ['F', 'M', 'M', 'F', 'M', 'M', 'F', 'M', 'F', 'F'],
    'Score': [91, None, 76, 84, 89, 95, None, 88, 93, 90]
}
df = pd.DataFrame(data)

In [ ]:
df.to_csv("raw_data.csv", index=False)
df

    Name   Age Gender  Score
0   Riya  28.0      F   91.0
1  Karan  30.0      M    NaN
2   None  22.0      M   76.0
3  Meena   NaN      F   84.0
4   Amit  26.0      M   89.0
5   None  21.0      M   95.0
6  Sneha   NaN      F    NaN
7  Vikas  24.0      M   88.0
8   Neha  29.0      F   93.0
9   Tina   NaN      F   90.0

In [ ]:
df.head()

    Name   Age Gender  Score
0   Riya  28.0      F   91.0
1  Karan  30.0      M    NaN
2   None  22.0      M   76.0
3  Meena   NaN      F   84.0
4   Amit  26.0      M   89.0

In [ ]:
df_dropped = df.dropna()
df_dropped

    Name   Age Gender  Score
0   Riya  28.0      F   91.0
4   Amit  26.0      M   89.0
7  Vikas  24.0      M   88.0
8   Neha  29.0      F   93.0

In [ ]:
print(df.isna().sum())

Name      2
Age       3
Gender    0
Score     2
dtype: int64

In [ ]:
df_filled = df.copy()
df_filled['Name'] = df_filled['Name'].fillna("some name")
df_filled['Age'] = df_filled['Age'].fillna(21)
df_filled

        Name   Age Gender  Score
0       Riya  28.0      F   91.0
1      Karan  30.0      M    NaN
2  some name  22.0      M   76.0
3      Meena  21.0      F   84.0
4       Amit  26.0      M   89.0
5  some name  21.0      M   95.0
6      Sneha  21.0      F    NaN
7      Vikas  24.0      M   88.0
8       Neha  29.0      F   93.0
9       Tina  21.0      F   90.0

In [ ]:
df_filled.to_csv("cleaned_data.csv", index=False)