In [ ]:
import pandas as pd
left = pd.DataFrame(
    {
        "key": ["K0","K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C1", "C2", "C3", "C4"],
        "D": ["D1", "D2", "D3", "D4"],
    }
)

result = pd.merge(left, right, on="key")
result

  key   A   B   C   D
0  K0  A0  B0  C1  D1
1  K1  A1  B1  C2  D2
2  K2  A2  B2  C3  D3
3  K3  A3  B3  C4  D4

In [ ]:
import pandas as pd
left = pd.DataFrame(
    {
        "key1": ["K0","K1", "K2", "K3"],
        "key2": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K2", "K3"],
        "key2": ["K0", "K1", "K2", "K3"],
        "C": ["C1", "C2", "C3", "C4"],
        "D": ["D1", "D2", "D3", "D4"],
    }
)

result = pd.merge(left, right, how="left", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
result = pd.merge(left, right, how="right", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
result = pd.merge(left, right, how="inner", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
result = pd.merge(left, right, how="outer", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C1  D1
1   K1   K1  A1  B1  C2  D2
2   K2   K2  A2  B2  C3  D3
3   K3   K3  A3  B3  C4  D4

In [ ]:
import pandas as pd
data = {'Car_Name': ['Tata', 'Mahindra', 'BYD', 'Tesla'],
        'Mileage(km)': [100, None, 200, None],
        'Country': ['Delhi', None, 'China', 'America'],
        'Fuel_Type': ['Petrol', 'Petrol', 'EV', 'EV']}
print(data)

{'Car_Name': ['Tata', 'Mahindra', 'BYD', 'Tesla'], 'Mileage(km)': [100, None, 200, None], 'Country': ['Delhi', None, 'China', 'America'], 'Fuel_Type': ['Petrol', 'Petrol', 'EV', 'EV']}

In [ ]:
df = pd.DataFrame(data)
print(df)

   Car_Name  Mileage(km)  Country Fuel_Type
0      Tata        100.0    Delhi    Petrol
1  Mahindra          NaN     None    Petrol
2       BYD        200.0    China        EV
3     Tesla          NaN  America        EV

Step-by-Step Data Cleaning Method
1. Check for Missing Data:
Shows which cells are missing(True)

In [ ]:
df.isna()  #it is used to check the null values in the dataframe

   Car_Name  Mileage(km)  Country  Fuel_Type
0     False        False    False      False
1     False         True     True      False
2     False        False    False      False
3     False         True    False      False

In [ ]:
df.isna().sum() #It is like an extension of isna() where we get the sum

Car_Name       0
Mileage(km)    2
Country        1
Fuel_Type      0
dtype: int64

2. Drop Missing Data

In [ ]:

df.dropna()  #it is used to drop the rows with null values and the output only shows the rows with zero null values

  Car_Name  Mileage(km) Country Fuel_Type
0     Tata        100.0   Delhi    Petrol
2      BYD        200.0   China        EV

Drop Columns with Nan/None or Null values

In [ ]:
df.dropna(axis=1)

   Car_Name Fuel_Type
0      Tata    Petrol
1  Mahindra    Petrol
2       BYD        EV
3     Tesla        EV

Drop Rows with Null values (default)

In [ ]:
df.dropna(axis = 0)

  Car_Name  Mileage(km) Country Fuel_Type
0     Tata        100.0   Delhi    Petrol
2      BYD        200.0   China        EV

3. Drop Rows with missing values

In [ ]:
df.dropna(subset=['Country'])

  Car_Name  Mileage(km)  Country Fuel_Type
0     Tata        100.0    Delhi    Petrol
2      BYD        200.0    China        EV
3    Tesla          NaN  America        EV

In [ ]:
df.at[1,'Mileage(km)']=150 #at method is used to update a particuar cell
df                            #at[index_no., Col_name] = new value

   Car_Name  Mileage(km)  Country Fuel_Type
0      Tata        100.0    Delhi    Petrol
1  Mahindra        150.0     None    Petrol
2       BYD        200.0    China        EV
3     Tesla          NaN  America        EV

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

4. Fill Missing values

In [ ]:
df.fillna('Unknown')  #fillna is used to fill values wherever null values are present

   Car_Name Mileage(km)  Country Fuel_Type
0      Tata       100.0    Delhi    Petrol
1  Mahindra       150.0  Unknown    Petrol
2       BYD       200.0    China        EV
3     Tesla     Unknown  America        EV

Rename Columns

In [ ]:
df.rename(columns={'Car_Name': 'Car_Brand'}, inplace=True)
df

  Car_Brand  Mileage(km)  Country Fuel_Type
0      Tata        100.0    Delhi    Petrol
1  Mahindra        150.0     None    Petrol
2       BYD        200.0    China        EV
3     Tesla          NaN  America        EV

In [ ]:
df['Car_Brand'] =df['Car_Brand'].str.upper()
df

  Car_Brand  Mileage(km)  Country Fuel_Type
0      TATA        100.0    Delhi    Petrol
1  MAHINDRA        150.0     None    Petrol
2       BYD        200.0    China        EV
3     TESLA          NaN  America        EV

In [ ]:
df['Car_Brand'] = df['Car_Brand'].str.lower()
df

  Car_Brand  Mileage(km)  Country Fuel_Type
0      tata        100.0    Delhi    Petrol
1  mahindra        150.0     None    Petrol
2       byd        200.0    China        EV
3     tesla          NaN  America        EV

5. Remove Outliers

In [ ]:
df = df[df['Mileage(km)'] < 200]

In [ ]:
df

  Car_Brand  Mileage(km) Country Fuel_Type
0      tata        100.0   Delhi    Petrol
1  mahindra        150.0    None    Petrol

USING CSV FILE

In [1]:
import pandas as pd
data = {'Name': ['Sachin', 'Sachin', 'Dravid', 'Dhoni', 'Virat', 'Jaiswal', 'Rohit', 'Jadeja', 'Bumrah'],
        'Age': [25, 25, '35', 40, 45, 50, 'nan', 'nan', 60],
        'Salary': [50000, 50000, 70000, 80000, 90000, 100000, 110000, 120000, 100000],
        'Rating': [4.5, 4.5, 4.2, 3.9, 4.8, 5.0, 4.2, 'nan', 'nan']
        }

# Save synth
df = pd.DataFrame(data)
df.to_csv('Demo_data4.csv', index=False)

In [2]:
print(data)

{'Name': ['Sachin', 'Sachin', 'Dravid', 'Dhoni', 'Virat', 'Jaiswal', 'Rohit', 'Jadeja', 'Bumrah'], 'Age': [25, 25, '35', 40, 45, 50, 'nan', 'nan', 60], 'Salary': [50000, 50000, 70000, 80000, 90000, 100000, 110000, 120000, 100000], 'Rating': [4.5, 4.5, 4.2, 3.9, 4.8, 5.0, 4.2, 'nan', 'nan']}

In [5]:
import pandas as pd
df = pd.read_csv('/content/Demo_data4.csv')
print("Original Data:")
print(df)

Original Data:
      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
1   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit   NaN  110000     4.2
7   Jadeja   NaN  120000     NaN
8   Bumrah  60.0  100000     NaN

In [4]:
newdf = df.fillna(22.00)
print(newdf)

      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
1   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit  22.0  110000     4.2
7   Jadeja  22.0  120000    22.0
8   Bumrah  60.0  100000    22.0

In [20]:
newdf.iloc[8, 3] = 6
newdf

      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
1   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit  22.0  110000     4.2
7   Jadeja  22.0  120000    22.0
8   Bumrah  60.0  100000     6.0

In [14]:
df.fillna({'Age': 85, 'Rating': 55}, inplace=False)

      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
1   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit  85.0  110000     4.2
7   Jadeja  85.0  120000    55.0
8   Bumrah  60.0  100000    55.0

In [15]:
print(df.duplicated())

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [16]:
df_cleaned = df.dropna()
df_cleaned

      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
1   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit  85.0  110000     4.2
7   Jadeja  85.0  120000    55.0
8   Bumrah  60.0  100000    55.0

In [17]:
a = df.drop_duplicates()     #it is used to remove duplicates from the row
print(a)

      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit  85.0  110000     4.2
7   Jadeja  85.0  120000    55.0
8   Bumrah  60.0  100000    55.0

In [18]:
missing_values = df.isnull().sum()
print(missing_values)

Name      0
Age       0
Salary    0
Rating    0
dtype: int64

In [22]:
print(df)

      Name   Age  Salary  Rating
0   Sachin  25.0   50000     4.5
1   Sachin  25.0   50000     4.5
2   Dravid  35.0   70000     4.2
3    Dhoni  40.0   80000     3.9
4    Virat  45.0   90000     4.8
5  Jaiswal  50.0  100000     5.0
6    Rohit  85.0  110000     4.2
7   Jadeja  85.0  120000    55.0
8   Bumrah  60.0  100000    55.0