### Introduction to Pandas Library

Creating Pandas Dataframes

In [3]:
import pandas as pd
left = pd.DataFrame(
    {
        "key":["K0", "K1", "K2", "AЗ"],
        "Α": ["Α0", "Α1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
       "key": ["K0", "К1", "K2", "К3"],
       "C": ["C0", "C1", "C2", "C3"],
       "D": ["D0", "D1", "D2", "D3"],
    }
)

result = pd.merge(left, right, on="key")

result

  key   Α   B   C   D
0  K0  Α0  B0  C0  D0
1  K2  A2  B2  C2  D2

### Merging two DataFrames on a single key

In [12]:
left=pd.DataFrame(
{
"key": ["K0", "K1", "K2", "A3"],
"A": ["A0", "A1", "A2", "A3"],
"B":["B0", "B1", "B2", "B3"],
}
)

right=pd.DataFrame(
{
"key": ["K0", "K1", "K2", "K3"],
"C": ["C0", "C1", "C2", "C3"],
"D": ["D0", "D1", "D2", "D3"],
}
)

result = pd.merge(left, right, on="key")

result

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2

In [8]:
left=pd.DataFrame(
{
"key1": ["K0", "K0", "K1", "K2"],
"key2": ["K0", "K1", "K0", "К1"],
"A": ["A0", "A1", "A2", "A3"],
"B":["B0", "B1", "B2", "B3"],
}
)

right=pd.DataFrame(
{
"key1": ["K0", "K1", "K1", "K2"],
"key2": ["K0", "K0", "K0", "K0"],
"C": ["C0", "C1", "C2", "C3"],
"D": ["D0", "D1", "D2", "D3"],
}
)

result = pd.merge(left, right, how="left", on=["key1", "key2"])

result

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   К1  A3  B3  NaN  NaN

In [9]:
result = pd.merge(left, right, how="right", on=["key1", "key2"])
result

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [10]:
result = pd.merge(left, right, how="outer", on=["key1", "key2"])
result

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   К1   A3   B3  NaN  NaN

In [11]:
result = pd.merge(left, right, how="inner", on=["key1", "key2"])
result

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [41]:
data = {'Name': ['Amal', 'John', 'Adinath', 'Megha'],
        'Age': [25, None, 30, None],
        'Gender': ['M', 'M', None, 'F']}


df = pd.DataFrame(data)
print(df)

      Name   Age Gender
0     Amal  25.0      M
1     John   NaN      M
2  Adinath  30.0   None
3    Megha   NaN      F

### Detecting Null values
The pandas.isna() function is used to detect missing or null values (represented as NaN, None, or NaT)

In [42]:
df.isna()

    Name    Age  Gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False

### Drop Rows with Any NaN

In [43]:
df.dropna()

   Name   Age Gender
0  Amal  25.0      M

### Drop Rows with Missing in Specific Column

In [44]:
 df.dropna(subset=['Age'])

      Name   Age Gender
0     Amal  25.0      M
2  Adinath  30.0   None

### Filling the missing values with mean

In [45]:
# Fill missing Age values with the mean
df["Age"].fillna(int(df["Age"].mean()), inplace=True)

# Fill missing Gender values with the mode
df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

C:\Users\amalv\AppData\Local\Temp\ipykernel_16032\3397637259.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(int(df["Age"].mean()), inplace=True)
C:\Users\amalv\AppData\Local\Temp\ipykernel_16032\3397637259.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

In [46]:
df

      Name   Age Gender
0     Amal  25.0      M
1     John  27.0      M
2  Adinath  30.0      M
3    Megha  27.0      F

#### Detect Duplicates

In [47]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

### Rename Columns

In [48]:
df.rename(columns={'Name': 'Full Name'}, inplace=True)
df

  Full Name   Age Gender
0      Amal  25.0      M
1      John  27.0      M
2   Adinath  30.0      M
3     Megha  27.0      F

### Standardize Text

In [50]:
df['Full Name'] = df['Full Name'].str.upper()
df

  Full Name   Age Gender
0      AMAL  25.0      M
1      JOHN  27.0      M
2   ADINATH  30.0      M
3     MEGHA  27.0      F

### Filtering texts in pandas

In [52]:
df2 = df[df["Gender"] == "M"]
df2

  Full Name   Age Gender
0      AMAL  25.0      M
1      JOHN  27.0      M
2   ADINATH  30.0      M

### Reading from csv file

In [55]:
### reading csv file
df3 = pd.read_csv("./data/test.csv")

In [56]:
df3.head()

   Roll             Name
0     1       ⁠Aaron Joy
1     2  ⁠Abhay Murali M
2     3       ⁠Abhinav A
3     4      ⁠Abhishek A
4     5      ⁠Achyutth K