**Data Cleaning**

Pandas basics

In [ ]:
import pandas as pd

In [ ]:

left=pd.DataFrame(
    {"key":['k0','k1','k2','k3'],
     "A":['A0','A1','A2','A3'],
     "B":['B0','B1','B2','B3']
     }
)
right=pd.DataFrame(
    {'key':['k0','k1','k2','k3'],
     'C':['C0','C1','C2','C3'],
     "D":['D0','D1','D2','D3']
     }
)
result=pd.merge(left,right,on='key')
result

  key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [ ]:
import pandas as pd
left=pd.DataFrame(
    {"key1":['k0','k1','k2','k3'],
    "key2":['k0','k1','k0','k1'],
     "A":['A0','A1','A2','A3'],
     "B":['B0','B1','B2','B3']
     }
)
right=pd.DataFrame(
    {'key1':['k0','k1','k2','k3'],
      'key2':['k0','k1','k0','k0'],
     'C':['C0','C1','C2','C3'],
     "D":['D0','D1','D2','D3']
     }
)
result=pd.merge(left,right,on=['key1','key2'])
result

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k1  A1  B1  C1  D1
2   k2   k0  A2  B2  C2  D2

**Note--sorting in pandas= df.sort_values(by=feature,ascending=True)

         .loc[]->df.loc[condition,'col1']=df.loc[condition,'col2']  
         df.loc[rowindexer,colindexer]**

In [ ]:
import pandas as pd
left=pd.DataFrame(
    {"key1":['k0','k1','k2','k3'],
    "key2":['k0','k1','k0','k1'],
     "A":['A0','A1','A2','A3'],
     "B":['B0','B1','B2','B3']
     }
)
right=pd.DataFrame(
    {'key1':['k0','k1','k2','k3'],
      'key2':['k0','k1','k0','k0'],
     'C':['C0','C1','C2','C3'],
     "D":['D0','D1','D2','D3']
     }
)
result1=pd.merge(left,right,how='left',on=['key1','key2'])
result1

  key1 key2   A   B    C    D
0   k0   k0  A0  B0   C0   D0
1   k1   k1  A1  B1   C1   D1
2   k2   k0  A2  B2   C2   D2
3   k3   k1  A3  B3  NaN  NaN

In [ ]:

result2=pd.merge(left,right,how='right',on=['key1','key2'])
result2

  key1 key2    A    B   C   D
0   k0   k0   A0   B0  C0  D0
1   k1   k1   A1   B1  C1  D1
2   k2   k0   A2   B2  C2  D2
3   k3   k0  NaN  NaN  C3  D3

In [ ]:

result3=pd.merge(left,right,how='outer',on=['key1','key2'])
result3

  key1 key2    A    B    C    D
0   k0   k0   A0   B0   C0   D0
1   k1   k1   A1   B1   C1   D1
2   k2   k0   A2   B2   C2   D2
3   k3   k0  NaN  NaN   C3   D3
4   k3   k1   A3   B3  NaN  NaN

In [ ]:

result4=pd.merge(left,right,how='inner',on=['key1','key2'])
result4

  key1 key2   A   B   C   D
0   k0   k0  A0  B0  C0  D0
1   k1   k1  A1  B1  C1  D1
2   k2   k0  A2  B2  C2  D2

**14/11------
1.Handling Missing Value**

In [ ]:
data={'name':['Abhiram','Arjun','Akshaya','sanju'],
      "Age":[25,None,30,None],
      "Gender":['M','M',None,'F']
}
print(data)
df=pd.DataFrame(data)
df

{'name': ['Abhiram', 'Arjun', 'Akshaya', 'sanju'], 'Age': [25, None, 30, None], 'Gender': ['M', 'M', None, 'F']}

      name   Age Gender
0  Abhiram  25.0      M
1    Arjun   NaN      M
2  Akshaya  30.0   None
3    sanju   NaN      F

**finding missing values**

In [ ]:
print(df.isna())
print(df.isna().sum()) #in each column wise count

    name    Age  Gender
0  False  False   False
1  False   True   False
2  False  False    True
3  False   True   False
name      0
Age       2
Gender    1
dtype: int64

**Deleting missing values**

In [ ]:
print(df.dropna())
print(df.dropna(axis=1)) #columns
print(df.dropna(axis=0)) #rows

      name   Age Gender
0  Abhiram  25.0      M
      name
0  Abhiram
1    Arjun
2  Akshaya
3    sanju
      name   Age Gender
0  Abhiram  25.0      M

In [ ]:
df.dropna(subset=['Gender'],inplace=False) #by specific column

      name   Age Gender
0  Abhiram  25.0      M
1    Arjun  32.0      M
3    sanju   NaN      F

In [ ]:
df.at[1,'Age']=32.0       #updating elements
df

      name   Age Gender
0  Abhiram  25.0      M
1    Arjun  32.0      M
2  Akshaya  30.0   None
3    sanju   NaN      F

In [ ]:
df = df.fillna(0)   # filling missing values with zero and assigning back to df
df

  Fullname   Age Gender
0  ABHIRAM  25.0      M
1    ARJUN  32.0      M
2  AKSHAYA  30.0      0
3    SANJU   0.0      F

In [ ]:
df.duplicated()
df
#df.drop_duplicated()

      name   Age Gender
0  Abhiram  25.0      M
1    Arjun  32.0      M
2  Akshaya  30.0   None
3    sanju   NaN      F

In [ ]:
df.rename(columns={'name':'Fullname'},inplace=True)   #Renaming the columns
df

  Fullname   Age Gender
0  Abhiram  25.0      M
1    Arjun  32.0      M
2  Akshaya  30.0   None
3    sanju   NaN      F

In [ ]:
#using upper and lower methods
df['Fullname'] = df['Fullname'].str.upper()
print(df)
df['Gender']=df['Gender'].str.lower()
print(df)

  Fullname   Age Gender
0  ABHIRAM  25.0      M
1    ARJUN  32.0      M
2  AKSHAYA  30.0      0
3    SANJU   0.0      F
  Fullname   Age Gender
0  ABHIRAM  25.0      m
1    ARJUN  32.0      m
2  AKSHAYA  30.0    NaN
3    SANJU   0.0      f

In [ ]:
#reading from csv file
df1=pd.read_csv("/content/Infosys_spring.csv")
df1

      Name   Age Gender Carholder
0    Arjun  23.0      M         Y
1  Anirudh  34.0    NaN         N
2   Sriram   NaN      M         Y
3    Aishu  21.0      F         Y
4  Abhiram  23.0      M       NaN
5  Akshaya  24.0      F       NaN

**week2**

In [ ]:
data1={'Name':['bhuvana','asritha','jyothika','nandhu','sanjay','yashna'],
       'Age':[23,45,23,12,34,56],
       'salary':[12000,23000,34000,6700,34000,23000],
       'Rating':[2.3,5.8,2.7,6.8,None,None]
}
df2=pd.DataFrame(data1)
df2.to_csv('demo.csv',index=False)

In [ ]:
df3=pd.read_csv('/content/demo.csv')
df3

       Name  Age  salary  Rating
0   bhuvana   23   12000     2.3
1   asritha   45   23000     5.8
2  jyothika   23   34000     2.7
3    nandhu   12    6700     6.8
4    sanjay   34   34000     NaN
5    yashna   56   23000     NaN

In [ ]:
df3.fillna({'Rating':0},inplace=False)
df_cleaned=df3.dropna()
df_cleaned

       Name  Age  salary  Rating
0   bhuvana   23   12000     2.3
1   asritha   45   23000     5.8
2  jyothika   23   34000     2.7
3    nandhu   12    6700     6.8

In [ ]:
df3.loc[len(df3)]=['nandhu',12,6700,6.8]
print(df3)
unique=df3.drop_duplicates()
unique

       Name  Age  salary  Rating
0   bhuvana   23   12000     2.3
1   asritha   45   23000     5.8
2  jyothika   23   34000     2.7
3    nandhu   12    6700     6.8
4    sanjay   34   34000     NaN
5    yashna   56   23000     NaN
6    nandhu   12    6700     6.8

       Name  Age  salary  Rating
0   bhuvana   23   12000     2.3
1   asritha   45   23000     5.8
2  jyothika   23   34000     2.7
3    nandhu   12    6700     6.8
4    sanjay   34   34000     NaN
5    yashna   56   23000     NaN